export type UsCity = {
  slug: string;
  city: string;
  state: string;
  to: string;
  toLabel: string;
  toFlag: string;
  fromLabel: string;
  esCorridorSlug: string;
};

export const US_CITIES: UsCity[] = [
  // Los Angeles → Central America
  {
    slug: "los-angeles-to-el-salvador",
    city: "Los Angeles",
    state: "CA",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "Los Angeles",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "los-angeles-to-guatemala",
    city: "Los Angeles",
    state: "CA",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "Los Angeles",
    esCorridorSlug: "eeuu-guatemala",
  },
  {
    slug: "los-angeles-to-honduras",
    city: "Los Angeles",
    state: "CA",
    to: "HN",
    toLabel: "Honduras",
    toFlag: "🇭🇳",
    fromLabel: "Los Angeles",
    esCorridorSlug: "eeuu-honduras",
  },
  // Washington DC area (large Salvadoran diaspora)
  {
    slug: "washington-dc-to-el-salvador",
    city: "Washington",
    state: "DC",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "Washington DC",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "washington-dc-to-honduras",
    city: "Washington",
    state: "DC",
    to: "HN",
    toLabel: "Honduras",
    toFlag: "🇭🇳",
    fromLabel: "Washington DC",
    esCorridorSlug: "eeuu-honduras",
  },
  // New York
  {
    slug: "new-york-to-guatemala",
    city: "New York",
    state: "NY",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "New York",
    esCorridorSlug: "eeuu-guatemala",
  },
  {
    slug: "new-york-to-honduras",
    city: "New York",
    state: "NY",
    to: "HN",
    toLabel: "Honduras",
    toFlag: "🇭🇳",
    fromLabel: "New York",
    esCorridorSlug: "eeuu-honduras",
  },
  {
    slug: "new-york-to-dominican-republic",
    city: "New York",
    state: "NY",
    to: "DO",
    toLabel: "Dominican Republic",
    toFlag: "🇩🇴",
    fromLabel: "New York",
    esCorridorSlug: "eeuu-republica-dominicana",
  },
  {
    slug: "new-york-to-el-salvador",
    city: "New York",
    state: "NY",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "New York",
    esCorridorSlug: "eeuu-el-salvador",
  },
  // Houston
  {
    slug: "houston-to-el-salvador",
    city: "Houston",
    state: "TX",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "Houston",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "houston-to-honduras",
    city: "Houston",
    state: "TX",
    to: "HN",
    toLabel: "Honduras",
    toFlag: "🇭🇳",
    fromLabel: "Houston",
    esCorridorSlug: "eeuu-honduras",
  },
  {
    slug: "houston-to-mexico",
    city: "Houston",
    state: "TX",
    to: "MX",
    toLabel: "Mexico",
    toFlag: "🇲🇽",
    fromLabel: "Houston",
    esCorridorSlug: "eeuu-mexico",
  },
  // Dallas
  {
    slug: "dallas-to-el-salvador",
    city: "Dallas",
    state: "TX",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "Dallas",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "dallas-to-mexico",
    city: "Dallas",
    state: "TX",
    to: "MX",
    toLabel: "Mexico",
    toFlag: "🇲🇽",
    fromLabel: "Dallas",
    esCorridorSlug: "eeuu-mexico",
  },
  // Miami
  {
    slug: "miami-to-honduras",
    city: "Miami",
    state: "FL",
    to: "HN",
    toLabel: "Honduras",
    toFlag: "🇭🇳",
    fromLabel: "Miami",
    esCorridorSlug: "eeuu-honduras",
  },
  {
    slug: "miami-to-dominican-republic",
    city: "Miami",
    state: "FL",
    to: "DO",
    toLabel: "Dominican Republic",
    toFlag: "🇩🇴",
    fromLabel: "Miami",
    esCorridorSlug: "eeuu-republica-dominicana",
  },
  {
    slug: "miami-to-guatemala",
    city: "Miami",
    state: "FL",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "Miami",
    esCorridorSlug: "eeuu-guatemala",
  },
  // Chicago
  {
    slug: "chicago-to-mexico",
    city: "Chicago",
    state: "IL",
    to: "MX",
    toLabel: "Mexico",
    toFlag: "🇲🇽",
    fromLabel: "Chicago",
    esCorridorSlug: "eeuu-mexico",
  },
  {
    slug: "chicago-to-guatemala",
    city: "Chicago",
    state: "IL",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "Chicago",
    esCorridorSlug: "eeuu-guatemala",
  },
  // San Francisco
  {
    slug: "san-francisco-to-el-salvador",
    city: "San Francisco",
    state: "CA",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "San Francisco",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "san-francisco-to-guatemala",
    city: "San Francisco",
    state: "CA",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "San Francisco",
    esCorridorSlug: "eeuu-guatemala",
  },
  // Boston
  {
    slug: "boston-to-el-salvador",
    city: "Boston",
    state: "MA",
    to: "SV",
    toLabel: "El Salvador",
    toFlag: "🇸🇻",
    fromLabel: "Boston",
    esCorridorSlug: "eeuu-el-salvador",
  },
  {
    slug: "boston-to-guatemala",
    city: "Boston",
    state: "MA",
    to: "GT",
    toLabel: "Guatemala",
    toFlag: "🇬🇹",
    fromLabel: "Boston",
    esCorridorSlug: "eeuu-guatemala",
  },
];

export function getUsCityBySlug(slug: string): UsCity | undefined {
  return US_CITIES.find((c) => c.slug === slug);
}
